### ISSUE TITLE
loki object storage config broken

### ISSUE THREAD

**Issue by 4n4nd** [observatorium/operator#31]
In loki object storage config:
```yaml
  objectStorageConfig:
    loki:
      accessKeyIdKey: aws_access_key_id
      bucketsKey: buckets
      endpointKey: endpoint
      regionKey: region
      secretAccessKeyKey: aws_secret_access_key
      secretName: loki-objectstorage
```
Only the `endpointKey` is actually read and relayed to the deployments as `S3_URL`, other parameters are not used.
To make this work, I set the `endpoint` to `http://ACCESS_KEY_ID:ACCESS_SECRET_KEY@S3_HOST:S3_PORT/BUCKET_NAME`
