### ISSUE TITLE
Observatorium operator cannot reconcile the CR correctly

### ISSUE THREAD

**Issue by clyang82** [observatorium/operator#50]
Observatorium operator cannot reconcile the CR correctly. for example: https://github.com/observatorium/operator/blob/master/example/manifests/observatorium.yaml#L52:L66 
```
  compact:
    enableDownsampling: false
    image: quay.io/thanos/thanos:v0.17.1
    replicas: 1
    retentionResolution1h: 1s
    retentionResolution5m: 1s
    retentionResolutionRaw: 14d
    version: v0.17.1
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
```
the current logic won't take the value of `enableDownsampling` `retentionResolution1h` `retentionResolution5m` `retentionResolutionRaw` and `volumeClaimTemplate` to do reconciling. I can add them. But I would like to discuss the correct approach. I think in operator, we should extend the [observatorium](https://github.com/observatorium/deployments/blob/master/components/observatorium.libsonnet) which extends from [thanos](https://github.com/observatorium/deployments/blob/master/components/thanos.libsonnet). current operator extends the kube-thanos.

@squat @kakkoyun What do you think?
