### ISSUE TITLE
Observatorium.spec.loki.volumeClaimTemplate ignored?

### ISSUE THREAD

**Issue by noseka1** [observatorium/operator#64]
I am trying to change the size of persistent volumes for Loki components. Here are the relevant parts of my configuration:

```
apiVersion: core.observatorium.io/v1alpha1
kind: Observatorium
metadata:
  name: observatorium
spec:
  loki:
    image: $(image_loki)
    replicas:
      compactor: 1
      distributor: 2
      ingester: 10
      querier: 10
      query_frontend: 2
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  objectStorageConfig:
    loki:
      endpointKey: endpoint
      secretName: loki-object-storage

...
```
Unfortunately, the PVCs created are always of size 250Mi and I am not able to change it.
