### ISSUE TITLE
Loki components compute resources are not configurable

### ISSUE THREAD

**Issue by 4n4nd** [observatorium/operator#71]
All loki components are deployed with a default compute resource limit

```yaml
resources: {
    requests: { cpu: '100m', memory: '100Mi' },
    limits: { cpu: '200m', memory: '200Mi' },
  }
```

These values are not very production environment friendly.
