### ISSUE TITLE
Pod affinity Support

### ISSUE THREAD

**Issue by clyang82** [observatorium/operator#8]
Currently, `Api` `Compact` `Ruler` and `store-memcached` do not support `podAntiAffinity`

`Query/thanos-query-frontend/store-shard` has the following 
```
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - thanos-query
          namespaces:
          - open-cluster-management-observability
          topologyKey: kubernetes.io/hostname
        weight: 100
```

`Recevie` has the following 
```
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - thanos-receive
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - observability-observatorium
          namespaces:
          - open-cluster-management-observability
          topologyKey: kubernetes.io/hostname
        weight: 100
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - thanos-receive
            - key: app.kubernetes.io/instance
              operator: In
              values:
              - observability-observatorium
          namespaces:
          - open-cluster-management-observability
          topologyKey: topology.kubernetes.io/zone
        weight: 100
```

Suggest to keep consistence to use the following:
```
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - xxx
          topologyKey: kubernetes.io/hostname
        weight: 30
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values: xxx
          topologyKey: topology.kubernetes.io/zone
        weight: 70
```

Any suggestions? @squat @metalmatze
