### ISSUE TITLE
Deploy-operator doc update

### ISSUE THREAD

**Issue by damobrisbane** [observatorium/operator#83]
In https://github.com/observatorium/operator/blob/master/docs/deploy-operator.md, instruction says "create project observatorium", then goes into other projects, before losing context:

1) 

```
....

#### Create Namespaces

```shell
kubectl create namespace observatorium
```

#### S3 storage endpoint and secret

For **testing purposes** you may use [minio](https://github.com/minio/minio) as described below.

```shell
kubectl create namespace observatorium-minio
....

<<< WE ARE NO LONGER IN NS "OBSERVATORIUM >>>
```

and 2)

_RBAC Configuration_, step apply service_account.yaml, is namespace default:

```
....
  name: observatorium-operator
subjects:
- kind: ServiceAccount
  name: observatorium-operator
  namespace: default

```

So where does the deployment of resources into namespace observatorium" actually start?
